---
title: "Lab practice quiz 8"
author: "Jennifer Gomez"
date: "November 12, 2016"
output: pdf_document
---

###QUESTIONs pg. 1

1) On it's own, GMA accounted for 26% of the variance in job performance ratings, R2 =.26, *F*(1,498)=175.08, *p*<.001. When conscientiousness was added, it accounted for an additional .10% of the variance sr2=.10, 95% CI[.05, .14]. With both GMA and conscientiousness the multiple regression model was R² = .36, 95% CI[.29, .41] F(2, 497) = 137.5, p < .01. Therefore, conscientiousness does contribute to job performance above and beyond GMA. 

2) On it's own, GMA accounted for 26% of the variance in job performance ratings, R2 =.26, *F*(1,498)=175.08, *p*<.001. When assessment centre ratings were added, they accounted for an additional .02% of the variance sr2=.02, 95% CI[.00, .04]. With both GMA and ac the multiple regression model was R² = .28, 95% CI[.21, .34] F(2, 497) = 95.6, p < .01. Therefore, ac does contribute to job performance above and beyond GMA. 

3) On it's own, GMA accounted for 26% of the variance in job performance ratings, R2 =.26, *F*(1,498)=175.08, *p*<.001. When graph was added, it accounted for .00% of the variance sr2=.00, 95% CI[-.00, .00]. Therefore, graphology does not contribute to job performance above and beyond GMA. 

I examined the extent to which conscientiousness scores, assessmenr centre scores, and graphology ratings each contributed to the prediction of job performance beyond general mental ability. GMA alone accounted for 26 percent of the variance R2 =.26, *F*(1,498)=175.08, *p*<.001.Conscientiousness accounted for an additional .10% of the variance sr2=.10, 95% CI[.05, .14], *p*<.001, bringing the total amount of variance accounted for to 36% R² = .36, 95% CI[.29, .41] F(2, 497) = 137.5, p < .001. Assessment centre ratings accounted for an additional .02% of the variance sr2=.02, 95% CI[.00, .04], *p*<.001. Graphology does not contribute to job performance above and beyond GMA sr2=.00, 95% CI[-.00, .00], *ns*. Therefore, if only one other predictor can be used it should be conscientiousness. 

##REGRESSION BLOCKS

1. On it's own, GMA accounted for 26% of the variance in job performance ratings, R2 =.26, 95% CI [.20, .32], *p*<.01. When conscientiousness was added, it accounted for an additional .10% of the variance sr2=.10, 95% CI[.05, .14]. With both GMA and conscientiousness the multiple regression model was R² = .36, 95% CI[.29, .41], *p* < .01. The delta R2 was significant at Delta R2 = .10, 95% CI [.05, .14], *p* < .01. Therefore, conscientiousness does contribute to job performance above and beyond GMA. Using the regression block yielded the same answers as above. 

2. On it's own, GMA accounted for 26% of the variance in job performance ratings, R2 =.26, 95% CI[.20, .32], *p*<.01. When assessment centre ratings were added, they accounted for an additional .02% of the variance sr2=.02, 95% CI[.00, .04].  The delta R2 was significant at Delta R2 = .02, 95% CI [-.00, .04], *p* < .01. With both GMA and ac the multiple regression model was R² = .28, 95% CI[.21, .34], p < .01. Therefore, ac does contribute to job performance above and beyond GMA. 

3.  On it's own, GMA accounted for 26% of the variance in job performance ratings, R2 =.00, 95% CI[.20, .32], *p*<.01. When assessment graph ratings were added, they accounted for no additional .variance. sr2=.00, 95% CI[-.00, .00]. The delta R2 was not significant at Delta R2 = .02, 95% CI [-.00, .00], *ns*. Therefore, graphology does not contribute to job performance above and beyond GMA. 

##CONFIDENCE INTERVALS
The mean for GMA is *M*=100 and mean for conscientiousness is *M*=120. The confidence interval for predicted performance scores at the mean GMA and mean conscientiousness is 95% CI[100.15, 101.85]. This means that the best estimate of population mean score *M*=101.00, 95% CI[100.15, 101.85].

##PREDICTION INTERVALS
The prediction interval for predicted performance scores at the mean GMA and mean conscientiousnes is *M*=101, 95% CI[82, 120.1]. This means that someone with a GMA of 100 and con score of 120 could have a job perf score as low as 81 or as high 120, with a 95% prediction rate. 